// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbnwlknztyhfahwenjym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJibndsa256dHloZmFod2VuanltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODA2NjAsImV4cCI6MjA2NjY1NjY2MH0.rFVnHHxVtoGCsRxI2vEZ9tjMK-MJeDijBzbidEV3dgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);